title: Test Page
author: SERBH
description: Testing the page creation
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
